name: 'Match Label Pull Request Action'
description: 'Ensure that the pull request has the required labels'
inputs:
  labels:
    description: 'the labels check on the Pull Request'
    required: true
  mode:
    description: 'the type of matching you require - [all, any, singular]'
    default: 'all'
    required: false
outputs:
  matchedLabels:
    description: 'labels that match the pull request'
runs:
  using: 'node20'
  main: 'dist/index.js'
