name: 'Test'
on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  test:
    uses: UKHomeOffice/sas-github-workflows/.github/workflows/npm-test.yml@28f2b81a559160ddca5f04d65de7bbd56ba8dc6d
