name: 'Test'
on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  test:
    uses: UKHomeOffice/sas-github-workflows/.github/workflows/npm-test.yml@fae67a70317d501bc443ff8e6da002bfa410cd76
